name: RogueLikeItems
version: '${project.version}'
main: me.xdanez.roguelikeitems.RogueLikeItems
api-version: '1.21.9'
author: xDaneZ
website: https://github.com/xdanez/RogueLikeItems
description: Paper Plugin adding random attribute modifiers for items

commands:
  rli:
    description: "RogueLikeItems commands"
    aliases:
      - roguelikeitems

permissions:
  roguelikeitems.reload:
    description: reload command
    default: op
  roguelikeitems.give:
    description: give command
    default: op