name: Build and Add to Release

on:
  create:
    tag:
      - 'release-*'

jobs:
  update-build-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Set release version variable
      id: vars
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/release-}" >> $GITHUB_ENV

    - name: Create or Update Release and Upload Artifact
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ env.RELEASE_VERSION }}
        files: target/RogueLikeItems-${{ env.RELEASE_VERSION }}.jar
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
